name: "WLCS - Azure Enterprise Infrastructure Destroy"

on:
  workflow_dispatch: # Handmatige startknop in GitHub om 16:00 uur!

permissions:
  id-token: write
  contents: read

jobs:
  destroy_addons:
    name: "Destroy Costly Addons (Azure Bastion Only)"
    runs-on: ubuntu-latest
    environment: 
      name: 'wlcs-infrastructure-production' # Handmatige goedkeuring per mail/knop!
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_USE_OIDC: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Azure Login Platform
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_PLATFORM }}

      - name: Terraform Init (Addons)
        working-directory: ./terraform/02_addons
        run: terraform init

      - name: Terraform Destroy (Addons Only)
        working-directory: ./terraform/02_addons
        run: |
          terraform destroy -auto-approve \
            -var "subscription_id_platform=${{ secrets.AZURE_SUBSCRIPTION_PLATFORM }}"
