name: "WLCS - Terraform Enterprise Network Destroy"

on:
  workflow_dispatch: # Dit zorgt voor de handmatige startknop in GitHub

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: "Azure Infrastructure Destroy"
    runs-on: ubuntu-latest
    environment: 
      name: 'wlcs-infrastructure-production' # Behoudt de handmatige goedkeuring per mail/knop!
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_PLATFORM }}
      use_oidc: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_PLATFORM }}

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Destroy
        working-directory: ./terraform
        run: |
          terraform destroy -auto-approve \
            -var "tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
            -var "client_id=${{ secrets.AZURE_CLIENT_ID }}" \
            -var "subscription_id_platform=${{ secrets.AZURE_SUBSCRIPTION_PLATFORM }}" \
            -var "subscription_id_dev=${{ secrets.AZURE_SUBSCRIPTION_DEV }}"
